# Database
spring:
   application:
      name: picpay_clone
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: password
      initialization-mode: always
   h2:
      console:
         enabled: true
   api:
      versao: 1.0.0

# JPA properties
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.H2Dialect
      format_sql: true
